/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import static Principal.DesvanMika.cn;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Esta clase es la representación de la relación NM entre pedido y manualidades
 *
 * @author Josete
 * @version 1.0 BETA
 */
public class LineasPedido extends javax.swing.JFrame {

    /**
     * La variable JFrame es una ventana auxiliar para poder y cerrar ventanas
     * auxiliares y la clave compo es la clave del componente
     */
    JFrame aux; //esta variable apuntará a la ventana auxiliar abierta para poder cerrarla
    int claveCompoSalvada;

    /**
     * Crea la ventana, cambia el titulo y el icono y muestra la tabla
     *
     * @param clave Es un entero que representa a la clave del pedido
     */
    public LineasPedido(int clave) {
        this.claveCompoSalvada = clave;
        setTitle("lineas del pedido - Desvan de Mika");
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/icono.jpg"));
        setIconImage(icon);

        initComponents();
        numeroPedido.setText(String.valueOf(clave));
        numeroPedido.setEnabled(false);
        muestraTabla("PEDIDO_Npedido", String.valueOf(claveCompoSalvada));

    }

    /**
     * Este metodo busca en la tabla en el campo que le pasamos por parametro,
     * el texto que tambien le pas samos por parametro
     *
     * @param Campo String nombre del campo en el que vamos a buscar
     * @param Busca String texto que vamos a buscar
     */
    private void muestraTabla(String Campo, String Busca) {
        String consulta;
        String respuesta[] = new String[4];

        tablaComMat.setEnabled(true);
        tablaComMat.setVisible(true);
        DefaultTableModel tcm = new DefaultTableModel();
        tcm.addColumn("Pedido");
        tcm.addColumn("Cod. Manualidad");
        tcm.addColumn("Nombre");
        tcm.addColumn("Cantidad");
        tablaComMat.setModel(tcm);

        consulta = "select lineaspedido.PEDIDO_Npedido, lineaspedido.MANUALIDAD_codManualidad, manualidad.Nombre, lineaspedido.cantidad\n"
                + "from lineaspedido, manualidad\n"
                + "where  (manualidad.codManualidad=lineaspedido.MANUALIDAD_codManualidad) and (lineaspedido.PEDIDO_Npedido=" + claveCompoSalvada + ")";

        try {
            Statement st = cn.createStatement();
            ResultSet resultado = st.executeQuery(consulta);
            while (resultado.next()) {
                respuesta[0] = numeroPedido.getText();
                respuesta[1] = resultado.getString(2);
                respuesta[2] = resultado.getString(3);
                respuesta[3] = resultado.getString(4);

                tcm.addRow(respuesta);
            }// fin del while
        } catch (SQLException ex) {
            Logger.getLogger(ColoresForm.class.getName()).log(Level.SEVERE, null, ex);
        } //fin del try-catch

    } //fin del metod

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codManualidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        numeroPedido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaComMat = new javax.swing.JTable();

        jMenuItem2.setForeground(new java.awt.Color(255, 0, 51));
        jMenuItem2.setText("ELIMINAR");
        jMenuItem2.setComponentPopupMenu(jPopupMenu1);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Cod Manualidad");

        jLabel2.setText("Cantidad ");

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonCerrar.setText("CERRAR");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        jLabel4.setText("Introduzca las manualidades del pedido ");

        numeroPedido.setEnabled(false);

        tablaComMat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaComMat.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tablaComMat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(35, 35, 35))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonGuardar)
                                        .addGap(14, 14, 14))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cantidad)
                                    .addComponent(codManualidad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addComponent(botonCerrar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codManualidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonCerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Al pulsar el boton cerrar, cierra la ventana actual
     *
     */
    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCerrarActionPerformed

    /**
     * El boton guardar prepara el insert y lo ejecuta y refresca la tabla
     *
     *
     */
    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed

        try {
            PreparedStatement orden = cn.prepareStatement("INSERT INTO lineaspedido(pedido_npedido, manualidad_codmanualidad, cantidad) values(?,?,?)");
            orden.setInt(1, this.claveCompoSalvada);
            orden.setString(2, codManualidad.getText());
            orden.setString(3, cantidad.getText());
            orden.executeUpdate();
            JOptionPane.showMessageDialog(null, "Guardado con Exito");
            codManualidad.setText("");
            cantidad.setText("");
            muestraTabla("PEDIDO_Npedido", String.valueOf(claveCompoSalvada));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Se produjo un error, revise los datos");
            Logger.getLogger(LineasPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonGuardarActionPerformed
    /**
     *
     * Esta opción es borrar, comprueba que hay una fila seleccionada, pregunta
     * si queremos borrar y si decimos que si borra prepara la orden delete
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        String orden;
        int fila;
        int respuesta;

        fila = tablaComMat.getSelectedRow();
        if (fila >= 0) {
            respuesta = JOptionPane.showConfirmDialog(null, "¿Seguro que que quiere borrar La manualidad " + tablaComMat.getValueAt(fila, 1) + " compuesto de " + tablaComMat.getValueAt(fila, 2) + "?");
            if (respuesta == 0) {
                orden = "DELETE FROM lineaspedido where PEDIDO_Npedido=" + claveCompoSalvada + " and COMPONENTE_codComponente=" + tablaComMat.getValueAt(fila, 1);
                PreparedStatement pst;
                try {
                    pst = cn.prepareStatement(orden);
                    pst.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(ColoresForm.class.getName()).log(Level.SEVERE, null, ex);
                }//fin del try catch
                muestraTabla("PEDIDO_Npedido", String.valueOf(claveCompoSalvada));

            }// fin del if internos

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila con el boton izquierdo");
        } // fin del if exterior
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField codManualidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numeroPedido;
    private javax.swing.JTable tablaComMat;
    // End of variables declaration//GEN-END:variables
}
