/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import static Principal.DesvanMika.cn;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 * esta clase solo sirve para abrir una ventana auxiliar y sacar un listado de abalorios
 * con los datos de materiales y colores
 * @author Josete
 */
public class ListadoAbalorios extends javax.swing.JFrame {

    private void buscaAbalorio() {
        String consulta;
        String respuesta[] = new String[6];
        consulta = "SELECT material.codMAterial, color.Colorprincipal, abalorio.Hecho_de, abalorio.tamaño, abalorio.Forma, material.cantidad   \n"
                + "FROM abalorio , material, color\n"
                + "where abalorio.MATERIAL_codMaterial=material.codMaterial and material.COLOR_idCOLOR=color.idCOLOR";

        DefaultTableModel modeloTela = new DefaultTableModel();
        modeloTela.addColumn("Nº Abalorio");
        modeloTela.addColumn("Color");
        modeloTela.addColumn("Hecho de");
        modeloTela.addColumn("Tamaño");
        modeloTela.addColumn("Forma");
        modeloTela.addColumn("Cantidad");

        tablaAbalorio.setModel(modeloTela);
        try {
            Statement st = cn.createStatement();
            ResultSet resultado = st.executeQuery(consulta);
            while (resultado.next()) {
                respuesta[0] = resultado.getString(1);
                respuesta[1] = resultado.getString(2);
                respuesta[2] = resultado.getString(3);
                respuesta[3] = resultado.getString(4);
                respuesta[4] = resultado.getString(5);
                respuesta[5] = resultado.getString(6);
                modeloTela.addRow(respuesta);
            } //Fin del while
            st.close();
            tablaAbalorio.setModel(modeloTela);
        } catch (SQLException ex) {
            Logger.getLogger(ClientesForm.class.getName()).log(Level.SEVERE, null, ex);
        } //fin del try-catch

    } // fin del metodo

    /**
     * el constructor crea la ventana, y le cambia el nombre a la ventan
     */
    public ListadoAbalorios() {
        initComponents();
        this.setTitle("Listado de Abalorios");
        buscaAbalorio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAbalorio = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tablaAbalorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaAbalorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAbalorio;
    // End of variables declaration//GEN-END:variables
}
