/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import static Principal.DesvanMika.cn;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 * Esta clase lo que hace es abrir una ventana ventana e imprime una lista de
 * telas.
 *
 * @author Josete
 */
public class ListadoTelas extends javax.swing.JFrame {

    private void buscaTela() {
        String consulta;
        String respuesta[] = new String[5];
        consulta = "SELECT material.codMAterial, color.Colorprincipal, tela.Tejido,tela.Estampado, material.cantidad   \n"
                + "FROM tela , material, color\n"
                + "where tela.MATERIAL_codMaterial=material.codMaterial and material.COLOR_idCOLOR=color.idCOLOR";

        DefaultTableModel modeloTela = new DefaultTableModel();
        modeloTela.addColumn("Nº Tela");
        modeloTela.addColumn("Color");
        modeloTela.addColumn("Tejido");
        modeloTela.addColumn("Estampado");
        modeloTela.addColumn("Cantidad");

        tablaTelas.setModel(modeloTela);
        try {
            Statement st = cn.createStatement();
            ResultSet resultado = st.executeQuery(consulta);
            while (resultado.next()) {
                respuesta[0] = resultado.getString(1);
                respuesta[1] = resultado.getString(2);
                respuesta[2] = resultado.getString(3);
                respuesta[3] = resultado.getString(4);
                respuesta[4] = resultado.getString(5);
                modeloTela.addRow(respuesta);
            } //Fin del while
            st.close();
            tablaTelas.setModel(modeloTela);
        } catch (SQLException ex) {
            Logger.getLogger(ClientesForm.class.getName()).log(Level.SEVERE, null, ex);
        } //fin del try-catch

    } // fin del metodo

    /**
     * crea la ventana, le cambia el nombre y saca la lista
     */
    public ListadoTelas() {
        initComponents();
        this.setTitle("Listado de Telas");
        buscaTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTelas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tablaTelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaTelas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTelas;
    // End of variables declaration//GEN-END:variables
}
